version: '3'

tasks:
  prepare:
    desc: "Run cargo check, fmt, clippy, build, and test"
    cmds:
      - cargo check
      - cargo fmt
      - cargo clippy
      - cargo build
      - cargo test

  install:
    desc: "Build in release mode and move the binary to /usr/local/bin"
    cmds:
      - cargo build --release
      - sudo mv target/release/shot /usr/local/bin/shot

  uninstall:
    desc: "Remove shot from /usr/local/bin"
    cmds:
      - sudo rm /usr/local/bin/shot

  test_cli:
    desc: "Run the CLI tests"
    cmds:
      - cargo build --release
      - ./target/release/shot -f example/declare_variable.blt -d > logs/declare_variable.log
      - ./target/release/shot -f example/declare_function.blt -d > logs/declare_function.log
